// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolarSharp.Reporting.EntityFrameworkCore;

#nullable disable

namespace PolarSharp.Reporting.EntityFrameworkCore.Sqlite.Migrations
{
    [DbContext(typeof(PolarReportingDbContext))]
    partial class PolarReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportBenefitGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BenefitId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BenefitKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("BenefitName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolarGrantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrderId");

                    b.HasIndex("TenantId", "PolarGrantId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CustomerId", "IsGranted");

                    b.ToTable("polar_report_benefit_grants", (string)null);
                });

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportCustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FirstOrderAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastOrderAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LifetimeValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolarCustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email");

                    b.HasIndex("TenantId", "LastOrderAt");

                    b.HasIndex("TenantId", "PolarCustomerId")
                        .IsUnique();

                    b.ToTable("polar_report_customers", (string)null);
                });

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolarEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.HasIndex("TenantId", "PolarEventId")
                        .IsUnique();

                    b.ToTable("polar_report_events", (string)null);
                });

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolarOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("RefundedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "PolarOrderId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CustomerId", "CreatedAt");

                    b.ToTable("polar_report_orders", (string)null);
                });

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportOrderLineItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscountAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LineTotal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("polar_report_order_line_items", (string)null);
                });

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportOrderRefundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolarRefundId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrderId");

                    b.HasIndex("TenantId", "PolarRefundId")
                        .IsUnique();

                    b.ToTable("polar_report_order_refunds", (string)null);
                });

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportSnapshotCheckpointEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPolarId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "Resource");

                    b.ToTable("polar_report_snapshot_checkpoints", (string)null);
                });

            modelBuilder.Entity("PolarSharp.Reporting.EntityFrameworkCore.Entities.ReportSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFakeData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolarSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PolarSubscriptionId")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status", "StartedAt");

                    b.ToTable("polar_report_subscriptions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
